#!/bin/sh

  
. /lib/lsb/init-functions 


JAVA_HOME="/usr/lib/jvm/jdk1.7.0_45/"


RUNNING_USER=baina


APP_HOME=/home/baina/pushmessage


APP_MAINCLASS=PushMessageService-1.0-SNAPSHOT.jar


#CLASSPATH=$APP_HOME/classes
#for i in "$APP_HOME"/lib/*.jar; do
 #  CLASSPATH="$CLASSPATH":"$i"
#done


JAVA_OPTS="-verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Xloggc:gc.log  -Xms2g -Xmx2g -XX:+UseG1GC  -XX:-OmitStackTraceInFastThrow -jar"


psid=0

checkpid() {
   javaps=`$JAVA_HOME/bin/jps -l | grep $APP_MAINCLASS`

   if [ -n "$javaps" ]; then
      psid=`echo $javaps | awk '{print $1}'`
   else
      psid=0
   fi
}


start() {
   checkpid

   if [ $psid -ne 0 ]; then
      echo "================================"
      echo "warn: $APP_MAINCLASS already started! (pid=$psid)"
      echo "================================"
   else
      echo -n "Starting $APP_MAINCLASS ..."
      cd $APP_HOME
      #JAVA_CMD="nohup $JAVA_HOME/bin/java $JAVA_OPTS  $APP_MAINCLASS >/dev/null 2>&1 &"
      JAVA_CMD="nohup /bin/bash  $APP_HOME/start.sh >/dev/null 2>&1 &"
      su $RUNNING_USER -c "$JAVA_CMD"  

      #nohup $JAVA_HOME/bin/java $JAVA_OPTS  $APP_MAINCLASS >/dev/null 2>&1 &
      checkpid
      if [ $psid -ne 0 ]; then
         echo "(pid=$psid) [OK]"
      else
         echo "[Failed]"
      fi
   fi
}


stop() {
   checkpid

   if [ $psid -ne 0 ]; then
      echo -n "Stopping $APP_MAINCLASS ...(pid=$psid) "
      su $RUNNING_USER -c "kill -9 $psid" 
      if [ $? -eq 0 ]; then
         echo "[OK]"
      else
         echo "[Failed]"
      fi

      checkpid
      if [ $psid -ne 0 ]; then
         stop
      fi
   else
      echo "================================"
      echo "warn: $APP_MAINCLASS is not running"
      echo "================================"
   fi
}


status() {
   checkpid

   if [ $psid -ne 0 ];  then
      echo "$APP_MAINCLASS is running! (pid=$psid)"
   else
      echo "$APP_MAINCLASS is not running"
   fi
}

info() {
   echo "System Information:"
   echo "****************************"
   echo `head -n 1 /etc/issue`
   echo `uname -a`
   echo
   echo "JAVA_HOME=$JAVA_HOME"
   echo `$JAVA_HOME/bin/java -version`
   echo
   echo "APP_HOME=$APP_HOME"
   echo "APP_MAINCLASS=$APP_MAINCLASS"
   echo "****************************"
}


case "$1" in
   'start')
      start
      ;;
   'stop')
     stop
     ;;
   'restart')
     stop
     start
     ;;
   'status')
     status
     ;;
   'info')
     info
     ;;
  *)
     echo "Usage: $0 {start|stop|restart|status|info}"
     exit 1
esac
exit 0
